### ISSUE TITLE
Script repository tool section

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#108]
There is a "Tool" category in the ScriptCategory enum API, but the RSPeer Script Repository does not have a tool section.

**Comment by Sphiinx** [comment]
@ZachHerridge This isn't really an enhancement since the ScriptCategory API contains the "TOOL" enum, but there isn't a category on the website repository for it.

**Comment by Sphiinx** [comment]
Moved to the RSPeer API issues [here](https://github.com/MaddoxDevelopment/RSPeer-Api/issues/31).
