### ISSUE TITLE
disable resizable

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#110]
too many idiots running tut script on resizable complaining its broken

**Comment by VladBots** [comment]
+1

**Comment by Jasper-ketelaar** [comment]
I think just having a red opaque overlay on the game canvas whenever you are running the client on resizable to tell you to stop using resizable or stuff won't work is a good solution.

**Comment by VladBots** [comment]
You make it a blocking event because you have to have resizable off for client to work?

**Comment by Jasper-ketelaar** [comment]
Yeah
