### ISSUE TITLE
GrandExchange.buy/sell problems with runescript

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#111]
Get errors like this sometimes:

Error: cc.h() b.o() | cc.h b.o cn.s bi.v client.fireScriptEvent org.rspeer.runetek.providers.RSClient.fireScriptEvent org.rspeer.runetek.api.component.GrandExchange.placeOffer org.rspeer.runetek.api.component.GrandExchange.placeOffer org.rspeer.runetek.api.component.GrandExchange.buy ManlyRunecrafter:213 org.rspeer.script.LoopTask.run org.rspeer.script.Script.run | java.lang.ArrayIndexOutOfBoundsException: -4 | 90 3408
Error: j.m() b.o() | j.m b.o cn.s bi.v client.fx client.aj ap.ao ap.run java.lang.Thread.run | java.lang.ArrayIndexOutOfBoundsException: -4 | 811 3300

These can occasionally cause client freezes.

Also another problem is that it will get stuck on a screen in the buying/selling process and it won't know how to recover from it.

**Comment by dQw4w9WgXcQ** [comment]
i get these errors but it never gets stuck or freezes

**Comment by Man16** [comment]
@dQw4w9WgXcQ I've only personally seen it freeze once but I guess its still possible.

Main irritating thing is the bit where it can get stuck in the middle of the process because its not entering the correct data in.

**Comment by dQw4w9WgXcQ** [comment]
its an issue on your end or with the ge api.  the runescript error itself doesn't cause freezes or other issues.

**Comment by Man16** [comment]
Blackscreening/freezing more often now.

**Comment by Jasper-ketelaar** [comment]
Mind showing me the code you're using that is causing these blackscreens/freezes so I could check it out?

**Comment by Man16** [comment]
@Jasper-ketelaar 

GrandExchange.buyByIncreasingPrice(setting.getEssenceType().getName(), geSession.getEssenceAmountToBuy(), Random.nextInt(8, 11))

Stuff like this.

**Comment by SPEN-CER** [comment]
That's the old G/E api, which is unchanged and going to be deprecated in the next build. Use the new methods, see #135

**Comment by SPEN-CER** [comment]
See the example that was proided in #135 
`public void example() {
        if (GrandExchange.createOffer(GrandExchangeOffer.Type.BUY)) {
            Time.sleepUntil(GrandExchangeSetup::isOpen, 500, 1500);
        }

        if (GrandExchangeSetup.isOpen()) {
            GrandExchangeSetup.setItem("Teak logs");
            GrandExchangeSetup.setQuantity(5);
            GrandExchangeSetup.confirm();
        }
}`
