### ISSUE TITLE
Magic.cast(Spell spell, Interactable interactable) does not handle all opcodes

### ISSUE THREAD

**Issue by rsMink** [rs-peer/issues#114]
int SPELL_ON_COMPONENT = 58; // 'Selected Spell' -> Widget
int SPELL_ON_ITEM = 32; // 'Selected Spell' -> Item
int BUTTON_SELECTABLE_SPELL = 25; // Type 2
int SPELL_ON_GROUND_ITEM = 17;
int SPELL_ON_PLAYER = 15;  // Using a 'Selected Spell' on a Player
int SPELL_ON_NPC = 8;  // Using a 'Selected Spell' on a NPC
int SPELL_ON_OBJECT = 2; // Using a 'Selected Spell' on a SceneObject

**Comment by SPEN-CER** [comment]
Should be working as expected in the next build
