### ISSUE TITLE
Area.contains bug

### ISSUE THREAD

**Issue by VladBots** [rs-peer/issues#128]
```
		Player p = Players.getLocal();
		if (p != null) {
			g.drawString(p.getPosition().toString(), 25, 50);
			g.drawString(Area.singular(new Position(2474, 3429, 0)).contains(p) + "", 25, 95);
			g.drawString(Area.singular(new Position(2474, 3429, 0)).getTiles().get(0) + "", 25, 110);
		}
```

The current player position is 2474, 3429, 0.
Area.singular(new Position(2474, 3429, 0)).contains(p) returns false.
Area.singular(new Position(2474, 3429, 0)).getTiles().get(0) is fine, it has the Position in it.

https://i.imgur.com/mJfHtGW.png

**Comment by SPEN-CER** [comment]
Fixed
