### ISSUE TITLE
Super low cpu mode methods in projection

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#129]
Can we get them.

**Comment by MadDevelop** [comment]
All it does is disable landscape and model rendering and set tick delay to 90.

**Comment by Man16** [comment]
Ok but if you have methods for low cpu mode, why not super low cpu mode

**Comment by dQw4w9WgXcQ** [comment]
Y two modes.  Who uses the first one just get rid of it

**Comment by Man16** [comment]
@dQw4w9WgXcQ Agree. Just get rid of low cpu mode and rename super low to low. Its only a 10 tick difference or w/e

**Comment by SPEN-CER** [comment]
Projection.setLowCPUMode sets the tick delay to 20, if you want super low just call setTickDelay(90)

I've also added super low to the bot menu bar
