### ISSUE TITLE
Blocking events sometimes dont run before script loop

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#133]
Most commonly the welcome screen solver doesnt execute before the script loop resulting in the script interacting with stuff whilst still on the welcome screen.

This can be a problem since things such as inventory contains methods return false in the welcome screen.

**Comment by Man16** [comment]
@VladBots I already have this.. I cant remember if welcome screen has a state.

        if (Game.getClient().getGameState() != Game.STATE_IN_GAME) {
            return 700;
        }

**Comment by Man16** [comment]
Still got this problem after even checking if the welcome screen widget is there at the top of my loop.
Not sure what to do.

**Comment by Man16** [comment]
Why did this get closed if it's still a problem

**Comment by SPEN-CER** [comment]
Are you sure? I fixed it and people I've asked have told me it's fine now

**Comment by Man16** [comment]
Yes I'm sure.

There was another issue that was open relating to the same problem where you commented that you fixed it. I tested it after supposed fix and left a comment there too saying that it hasn't.
