### ISSUE TITLE
isAnimating returning true incorrectly.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#134]
isAnimating returns true even when the local player is not animating and returns an animation of -1. 
![screen shot 2018-07-22 at 5 34 32 pm](https://user-images.githubusercontent.com/11341771/43051393-8515210a-8dd6-11e8-9fcf-929da5d89970.png)

**Comment by SPEN-CER** [comment]
Use `getAnimation() == -1` for now. The current `isAnimating()` method was build to handle animations which have "resets" in them, but unfortunately that did not work as intended.
