### ISSUE TITLE
Interfaces.processContinue not continuing

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#137]
Interfaces.processContinue() is not able to process this specific dialogue.
Interfaces.canContinue returns false on this dialogue.

![screen shot 2018-07-22 at 9 07 38 pm](https://user-images.githubusercontent.com/11341771/43055359-808cd12e-8df3-11e8-8d3f-271173547f1c.png)

**Comment by dQw4w9WgXcQ** [comment]
Game.getClient().fireScriptEvent(299, 1, 1);

**Comment by SPEN-CER** [comment]
Use `Game.getClient().fireScriptEvent(299, 1, 1);` as a workaround for now.
