### ISSUE TITLE
add Bank#depositWornItems

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#14]

**Comment by dQw4w9WgXcQ** [comment]
parent 12 component 43

**Comment by dQw4w9WgXcQ** [comment]
also set withdraw mode noted 12, 34

**Comment by Speniser** [comment]
I've added the following functions to the API for the next build
Bank.depositInventory()
Bank.setRearrangeMode(Bank.RearrangeMode mode)
Bank.setWithdrawMode(Bank.WithdrawMode mode)
