### ISSUE TITLE
Add DepositBoxes

### ISSUE THREAD

**Issue by anondinh** [rs-peer/issues#140]
i got the locations and if they are f2p or p2p for you already 

` DRAYNOR_VILLAGE(new Tile(3094, 3241), false),
    EDGEVILLE(new Tile(3098, 3498), false),
    PORT_SARIM(new Tile(3045, 3235), false),
    VARROCK_WEST(new Tile(3180, 3434), false),
    LUMBRIDGE_TOP(new Tile(3209, 3217, 2), false),
    FALADOR_EAST(new Tile(3018, 3357), false),
    FALADOR_WEST(new Tile(2944, 3368), false),
    ARDOUGNE_NORTH(new Tile(2613, 3333), true),
    ARDOUGNE_SOUTH(new Tile(2654, 3281), true),
    CATHERBY(new Tile(2729, 3492), true),
    SEERS_VILLAGE(new Tile(2807, 3439), true),
    YANILLE(new Tile(2611, 3089), true);`

**Comment by MalikDz** [comment]
Added
