### ISSUE TITLE
login handler stuck after auth screen is opened and closed

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#147]
https://streamable.com/3splr

**Comment by Jasper-ketelaar** [comment]
Maybe you should enter the auth?

**Comment by dQw4w9WgXcQ** [comment]
sry the first vid got clipped, i edited it to show the issue

**Comment by dQw4w9WgXcQ** [comment]
https://i.imgur.com/E1dNSPy.png

game stat 11 after auth is opened and closed
