### ISSUE TITLE
Output Log into console as well

### ISSUE THREAD

**Issue by Infinitay** [rs-peer/issues#148]
I have a suggestion to output anything from `Log` (`Log::info`) into the console as well. Not really important, but would be nice to have it displayed into the console while developing

![image](https://user-images.githubusercontent.com/6964154/43179260-df2de288-8f9f-11e8-9e31-b29be3b8d851.png)
```
	@Override
	public void onStart() {
		Log.info("Loading GUI for " + getMeta().name() + " v" + getMeta().version() + "...");
		gui = new InfiniteBlackjackGUI(this);
		submit(TASKS);
	}
```

**Comment by SPEN-CER** [comment]
Use System.out.println
