### ISSUE TITLE
Add inDialogue() method

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#149]
Currently im checking it like this but its dumb

    private boolean inDialogue() {
        return Interfaces.isViewingChatOptions() || Interfaces.isViewingChat() || Interfaces.canContinue();
    }

I'm sure theres a better way.
@SPEN-CER said checking if the continue component is not null but that doesnt work.

**Comment by SPEN-CER** [comment]
Does `Interfaces.isDialogOpen()` not work?
