### ISSUE TITLE
Inventory.isEmpty() missing from API

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#154]
I think the method `Inventory.isEmpty()` has been forgotten.
Bank has `isEmpty()` but Inventory does not yet have this extremely useful method.

**Comment by nathangemieee** [comment]
if(!inventory.isfull)????

**Comment by Jasper-ketelaar** [comment]
Inventory can also not be full when it has 1 to 27 items in it @nathangemieee. Anyway Inventory.getCount() == 0 is probably what you are after.

**Comment by nathangemieee** [comment]
https://www.youtube.com/watch?v=rUyqwFO40So

**Comment by Jasper-ketelaar** [comment]
What's sugondese

**Comment by NeerOC** [comment]
```
private boolean isEmpty()
    {
        return Inventory.getCount() == 0;
    }
```

**Comment by troy-lamerton** [comment]
I appreciate all the replies. I've now used `Inventory.getCount() == 0`.

When I read that in code, it doesn't exactly roll off the tongue. When I read `Inventory.isFull()`, I feel a little bit warm inside. It would be great to have the same thing for `.isEmpty()`.

**Comment by SPEN-CER** [comment]
Added
