### ISSUE TITLE
isResizableMode throws AbstractMethodError

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#157]
![screen shot 2018-07-27 at 7 25 44 am](https://user-images.githubusercontent.com/11341771/43323300-7a999f6c-916e-11e8-89e3-502f88153456.png)

**Comment by SPEN-CER** [comment]
Resizable mode is not supported, so this hook will probably not be fixed for a while

**Comment by MadDevelop** [comment]
^ He wants to check to see if its enabled so he can show a warning in his script. @SPEN-CER

**Comment by Sphiinx** [comment]
I understand resizable is not supported, but I was planning to use the hook to set the client to fixed mode for users or warn them and stop the script/pause it.

**Comment by Sphiinx** [comment]
Thanks Mad, you beat me to it lol

**Comment by SPEN-CER** [comment]
I'll probably edit the client preferences file before loading the game instead, so the game is always started in fixed mode. In addition to this, I'll see if I can disable resizable mode entirely.

**Comment by Sphiinx** [comment]
@SPEN-CER That would work even better, thanks!

**Comment by Sphiinx** [comment]
Jagex now sets new RS accounts to resizable mode by default.

@SPEN-CER Please implement the fix mentioned above ASAP as this breaks a lot of things.

**Comment by SPEN-CER** [comment]
Resizable mode is disabled entirely in the next build, which is going to be out today or tomorrow (31st/1st)

**Comment by SPEN-CER** [comment]
So for now I've been able to disable entering resizable mode from within the game, but not if the game is started in resizable mode. Until then, please make use of `Game.getClientPreferences().getResizable()` (Returns 1 when in fixed mode, and 2 when in resizable)

**Comment by Sphiinx** [comment]
@SPEN-CER What about the changes Jagex made where any new RS account is set to Resizable mode by default upon first login?
