### ISSUE TITLE
Add getMembershipRemaining()

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#159]
Varps.get(263) returns number of days for membership.

Change the method name to w/e u want.

**Comment by Man16** [comment]
This varp is buggy if you start it whilst already logged in or you world hop because it returns 0.

@SPEN-CER Is it possible that another varp represents the value?

**Comment by Krulvis** [comment]
I believe it's only obtained once welcome screen has been opened (this also sets the varp), too unreliable to add to API imho

**Comment by SPEN-CER** [comment]
In that case I probably won't add it. With that being said, I am currently preparing large scale runescript update, which I believe will make it a little nicer to get this data.

**Comment by Man16** [comment]
thanks me
