### ISSUE TITLE
Improve submitting scripts to SDN.

### ISSUE THREAD

**Issue by MadDevelop** [rs-peer/issues#163]
Admin - Give ability to remove submissions / fix url.

FrontEnd - 
Show error if submitting wrong url (must be rspeer-public-sdn link)

Api -
Allow api to handle edge cases where the wrong path in the repo is submitted (possibly backtrace to the root level)

**Comment by MadDevelop** [comment]
Probably not due to one main issue.

1. The compiler is in C#, and its not very easy to read java annotations.

We would have to either make the submitting go through a java server (would rather not do, as its another thing to host and maintain), or result to text parsing (which can get ugly)

**Comment by troy-lamerton** [comment]
Can we come at it from another angle then? What if the submit script form is the source of truth. When you put the description in there, it updates for rspeer clients.

**Comment by MadDevelop** [comment]
@troy-lamerton It does do this for repository scripts, it reads off your manifest for local scripts.

**Comment by MadDevelop** [comment]
Updated the submission process to to automatically parse the url for the valid bits it needs.

You can now submit any part of it and it will find the correct url.

Example: https://gitlab.com/rspeer-public-sdn/MadDev/MadSandCrabs/blob/master/src/org/maddev/SandCrabs.java will now work.

Also added a few more error messages if you submit a url from the wrong project, invalid forum url, etc.

**Comment by troy-lamerton** [comment]
@MadDevelop that file/repo example is private
