### ISSUE TITLE
Webwalker Lumbridge null build path

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#166]
Webwalker returns a null build path on the second floor north stairs of the Lumbridge castle.

![screen shot 2018-07-30 at 10 50 57 am](https://user-images.githubusercontent.com/11341771/43411204-c17b4442-93e6-11e8-8258-6edd4c21bf49.png)

**Comment by SPEN-CER** [comment]
Where are you building the path to?

**Comment by Sphiinx** [comment]
BankLocation.getNearest();

**Comment by SPEN-CER** [comment]
Closed as duplicate of #156
