### ISSUE TITLE
RSPeer Repository Questing/Quest section

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#168]
The RSPeer Script Repository does not have a "Questing/Quest" section.

**Comment by nathangemieee** [comment]
use the other tabs???

**Comment by Sphiinx** [comment]
@nathangemieee What do you mean? Where do you expect someone to upload their quest script?

**Comment by nathangemieee** [comment]
on "others" just like every botting website?

**Comment by Sphiinx** [comment]
@nathangemieee I don't see a point for that considering there is already a QUEST enum in the ScriptCategory enum API.

**Comment by nathangemieee** [comment]
https://www.autismspeaks.org/what-autism/treatment

**Comment by MadDevelop** [comment]
Good find, ill add it.

**Comment by troy-lamerton** [comment]
@MadDevelop Quick reminder. This is not on the script repository site yet.
