### ISSUE TITLE
[BUG] Banking in Varrock West tries to use the deposit box

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#172]
The script author intended for a **full bank** to be opened, but the api is interacting with a deposit box and gets stuck.

<img width="101" alt="screen shot 2018-07-31 at 22 11 07" src="https://user-images.githubusercontent.com/13446008/43484508-d238fd78-950e-11e8-9523-bc54017643bf.png">

Deposit box marked in red circle.

**Comment by MalikDz** [comment]
Do you mind posting the code you're using ?
Both of these work just fine for me: 

`
		Bank.open(BankLocation.getNearestBooth());
		Bank.open(BankLocation.VARROCK_WEST);`

**Comment by Sphiinx** [comment]
@MalikDz You can close this actually. I was using BankLocation.getNearest(); without realizing that would also include deposit boxes since they're a bank location type.

I've changed it to use BankLocation.getNearestWithdrawable();

**Comment by SPEN-CER** [comment]
`Bank.open()` was changed to only open withdrawable banks a while ago, I guess that fix isn't out yet

**Comment by Sphiinx** [comment]
@SPEN-CER Oh, that also makes sense.
