### ISSUE TITLE
Script Changelog

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#174]
A feature to display a change log under a script details section in the repository that is automatically pulled from your git commit messages. It could display the newest script update commit message or all of the script updates commit messages along with the version number.

This would allow users who don't visit the forums regularly to know when a script has been updated that includes a fix for something, new feature, etc. Although, It could possibly end up being a mess though with everyone using different formatting for commit messages, not providing them, etc.

**Comment by Sphiinx** [comment]
Moved to the RSPeer API issues [here](https://github.com/MaddoxDevelopment/RSPeer-Api/issues/32).
