### ISSUE TITLE
add Equipment#Interact(Predicate<? super Identifiable>, ...)

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#175]

**Comment by dQw4w9WgXcQ** [comment]
or maybe predicate<string> at least.  idk, maybe we should have a peer for itemdef that implements identifiable or something?

**Comment by SPEN-CER** [comment]
My answer to this is the same as #63 

An update on the situation is that it may be possible to shadow-open the equipment tab. Only if this is the case I can add said mwthod
