### ISSUE TITLE
Bank.contains() returns false incorrectly sometimes

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#181]
I'm not sure how to reproduce this but I have it so that my script goes to the GE when it is out of supplies for something and when I manually check the amount in the bank, it is higher than 0.

So getCount is returning the incorrectly value sometimes and I'm not sure how to reproduce it.

**Comment by anthonypuppo** [comment]
Try adding a small delay (100 milliseconds or so) before using the Bank API after it opens. I've also experienced weird return values if I don't give use a delay.

**Comment by Man16** [comment]
@anthonypuppo The point is that it shouldn't be like that.

**Comment by Jasper-ketelaar** [comment]
Are you using Bank.getCount() or Bank.getCount(Predicate). If using Predicate, can you show me it?

**Comment by Man16** [comment]
@Jasper-ketelaar I'm passing a string to the method.

**Comment by Man16** [comment]
The bank class needs to be reverted back to using item tables for some stuff instead of interfaces completely until its sorted out. I dont think it will be possible to use interfaces with the bank unless you want to start implementing using the scroll bar etc.

I have found that putting the items required near the top of your bank helps to reduce the chances of this bug happening.

**Comment by troy-lamerton** [comment]
I am also experiencing this bug. Will have to add a small delay after the bank opens, which is annoying, because the script uses the bank very often, so GP/hr will suffer.

**Comment by SPEN-CER** [comment]
Should be fixed for the next build
