### ISSUE TITLE
AccountType and getFreeSlots

### ISSUE THREAD

**Issue by Blogans** [rs-peer/issues#182]
Two additions to the api that might benefit people in the future. I know I'm personally using these. 
`    public static int getFreeSlots(){
        return 28 - Inventory.getItems().length;
    }
`
`public static AccountType getAccountType(){
        Varpbit type = Varps.getBit(1777);
        switch (type.getValue()){
            case 1:
                return AccountType.IRONMAN;
            case 2:
                return AccountType.ULTIMATE_IRONMAN;
            case 3:
                return AccountType.HARDCORE_IRONMAN;
        }
        return AccountType.NORMAL;
    }`

**Comment by MalikDz** [comment]
Added for next build, thanks !
