### ISSUE TITLE
Inventory#getCount(boolean includeStackSize, Predicate<Item>)

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#19]
currently there is only getCount(boolean, int/string)

**Comment by SPEN-CER** [comment]
getCount uses ItemTables which do not use Item. 

I will add this, but it will not work if a secondary inventory is active (until #7 is fully solved), or if the inventory is closed.

The other "solution" is to split Item into Item & ComponentItem, which extends Item. This could break a large amount of existing scripts and other API code, so I will avoid doing this.
