### ISSUE TITLE
Timer class flaw

### ISSUE THREAD

**Issue by Blogans** [rs-peer/issues#191]
Had some issues regarding sleepUntil
` Time.sleepUntil(() -> name != null && Interfaces.isOpen(name.getIndex()), () -> Players.getLocal().isMoving(), 500, 700);`
will just stop the bots functionality. Yes btw, sitll learning the interface api.
The sleepUntil will work if there is something to delay it eg.
` Time.sleepUntil(() -> name != null && Interfaces.isOpen(name.getIndex()), () -> {
                        Time.sleep(100); or a println etc
                        return Players.getLocal().isMoving();
                    }, 250, 1000);`

**Comment by dQw4w9WgXcQ** [comment]
what the fuck

**Comment by SPEN-CER** [comment]
what is name

**Comment by Blogans** [comment]
An interface component, specific the enter name interface from a POH portal

**Comment by SPEN-CER** [comment]
isOpen is for root indices not component indices so that condition will never pass

**Comment by Blogans** [comment]
so would it be more viable to use isDisplayed?

**Comment by SPEN-CER** [comment]
No. Use isVisible. If that component is always classed as visible you may need to try a different component
