### ISSUE TITLE
Web walking fails to interact with door that is in another region

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#196]
[Here is a video of the issue, with movement debug on](https://my.pcloud.com/publink/show?code=XZpelW7Zz0dxQ9VbXSQiB4q7UW7zyjH1TeB7)

It tries to open a door that is in the next region.

![screen shot 2018-08-07 at 22 45 11](https://user-images.githubusercontent.com/13446008/43801534-a60089f8-9a93-11e8-949e-270971e34abf.png)

It doesn't realise that there is a problem, and will keep logging the same thing.

**Comment by LoganRS** [comment]
You came across that too huh?

**Comment by troy-lamerton** [comment]
Found another place where this happens:

Lumbridge swamp to Lumbridge Graveyard (the enclosed room with coffin)
![screen shot 2018-08-08 at 09 06 52](https://user-images.githubusercontent.com/13446008/43821808-6c99bd90-9aea-11e8-8226-6072d8bf58b5.png)

As I type this, ~30 seconds have passed and now it started walking again.

**Comment by LoganRS** [comment]
Haha, you're pretty much finding the same places as I was. Another place it happens is here on the area I made on the map. It was trying to automatically walk to Lumbridge upstairs to use the spinner and gets stuck unless its outside the gated area a few steps. 

![s](https://user-images.githubusercontent.com/26036465/43822065-fec1f818-9ab8-11e8-8b82-dfe9bffd2d50.png)
