### ISSUE TITLE
Login logged into the first account used, not the current account

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#200]
After afking and eventually getting logged out, RSPeer logged into a different account, which I had previously used.

**Expected behaviour:**
RSPeer relogs into the current account

**Comment by d-o-g** [comment]
it logs into the account u started with, unless u call setAccount

**Comment by Jasper-ketelaar** [comment]
I don't think this is unintended.

**Comment by SPEN-CER** [comment]
are you sure you started the script with April and not Brad? RSPeer only knows about the account that you started the script with

**Comment by troy-lamerton** [comment]
I guess it's possible. I often start a script while login is loading. That would make sense then.

**Comment by gwlvr** [comment]
I get this problems often now. Happened 3 times today on different mashines / scripts.

**Comment by Jasper-ketelaar** [comment]
Should be fixed in next release.
