### ISSUE TITLE
Auto Retaliate Methods

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#201]
Methods for determining whether auto-retaliate is active/inactive in addition to enabling/disabling auto-retaliate.

Varp: 172
Auto-retaliate on: 172 -> 0
Auto-retaliate off: 172 -> 1

**Comment by Jasper-ketelaar** [comment]
Are you sure 0 = on?

**Comment by Sphiinx** [comment]
I'm pretty sure unless I'm reading the varps incorrectly? I thought it seemed a bit odd at first too.

https://i.gyazo.com/d7cdfa743446dab2182cfe9b5d579faa.mp4

**Comment by Jasper-ketelaar** [comment]
I guess it's because the default state is auto retaliate on or something. Anyways, added!
