### ISSUE TITLE
Combat.select() not working

### ISSUE THREAD

**Issue by DrManhatan** [rs-peer/issues#203]
Combat.selected() doesn't seem to work. I got this on a loop, and it just keep printing whatever style it was to begin with.

```
            final int SCIMMY_SHARED = 12;
            if (Combat.getSelectedStyle() != SCIMMY_SHARED) 
                    Combat.select(SCIMMY_SHARED);
            
            Log.info("Combat style: " + Combat.getSelectedStyle()); // Combat style: 4
```

EDIT:
Okay, just after I created this issue I found the issue about adding these functions:
https://github.com/rs-peer/issues/issues/139

After being able to read the source I discover that I can indeed select combat style. But **getSelectedStyle,** and **select** are not uniform.

In this case
**Combat.select(3)** 
Equals
**Combat.getSelected() == 12**

As such I'd request to make the functionalities of the class uniform.

**Comment by Jasper-ketelaar** [comment]
Fixed in next revision. Combat.getSelected() will return between 0 and 3 for the selected style. Combat.select will take values between 0 and 3 to select a style.
