### ISSUE TITLE
DeathListener is called when the player did not die

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#204]
Registered class with a DeathListener was notified, but the player did not die.

It happened while walking. I will update this issue if it happens again.

### It was triggered by a random event!
![It was triggered by a random event!](https://media.giphy.com/media/WgPpJWrNS5XWXJTANC/giphy.gif)

When I continued the script a few minutes later, and the random event NPC was gone, the DeathListener was notified again (twice).

I just ran it again, and it is working fine now.

### Second occurance, close to the first one
<img width="765" alt="screen shot 2018-08-10 at 22 34 03" src="https://user-images.githubusercontent.com/13446008/43980217-9c866788-9ced-11e8-8d5d-2055e44a211b.png">

**Comment by Man16** [comment]
I've had issues with the death listener too but I've never been there to witness it.

It will sometimes be called twice for the local player dying or not at all (mostly the latter).

**Comment by troy-lamerton** [comment]
@SPEN-CER 
> Does this only happen for the local player? or all players?

Wait a minute.. Is DeathEvent called for any player that dies? I assumed it was only the local player.

**Comment by Jasper-ketelaar** [comment]
DeathEvent works for any PathingEntity. That includes the local player, any other player or any Npc.
