### ISSUE TITLE
Time.sleepUntil is broken

### ISSUE THREAD

**Issue by unerk** [rs-peer/issues#206]
Occasionally I will call Time.sleepUntil and the bot just terminates itself. As in, the stop button greys out, and pause changes to play, and the paint deregisters itself (which is written into my onStop method). No exceptions are thrown in the log, and based on the logging messages, the last thing that's called is the sleepUntil (each loop is guaranteed to print a new message).

Also this:

https://imgur.com/a/JrhU8Jq

2 other guys with sleepUntil problems

**Comment by MadDevelop** [comment]
Can you paste the code you are using with it?

**Comment by unerk** [comment]
```
                interactWithFurnace();
                Log.info("Finished walking to furnace, waiting for button");
                Time.sleepUntil(() -> Interfaces.getComponent(270, 14) != null, 300, 10000);
```
got here and then the script killed itself. Logged the "Finished walking to furnace" stuff too.

This happens sporadically, maybe once or twice per day per bot.

**Comment by unerk** [comment]
the problem is solved, turns out that if the sleep from the last bot is left over and it ends, it comes around and bites the new bot, which then dies.
