### ISSUE TITLE
Purge client logs

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#207]
The number of client logs that get saved grows very quickly which takes up quite a lot of space. I noticed I currently have 34 saved logs that add up to 885mb which is quite a lot considering how recently saved logs were added.

Perhaps only the last 10 logs should be kept or they should be purged automatically after a certain amount of time?

**Comment by anthonypuppo** [comment]
These should definitely be truncated. I'd say 10 MB or so would be a large enough daily log file size with another 10 or so max saved files.

**Comment by Jasper-ketelaar** [comment]
Yeah, I can do this.
