### ISSUE TITLE
Magic.cast() selects wrong action

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#208]
I'm unsure of what seems to trigger it, but occasionally Magic.cast(Spell) will switch to executing the second or third option of a spell in the spellbook. It's not a single occurrence either, when it happens it will continue to execute the same incorrect spell action if Magic.cast() is called again. The only way to fix it is to restart the script.

For example, if the were a magic bot that repeatedly executed Magic.cast(Spell.Modern.VARROCK_TELEPORT) whatever seems to trigger this will cause it to begin executing the second or third action of the spell. In this case, it would repeatedly try to execute the "Grand Exchange" teleport action of "Spell.Modern.VARROCK_TELEPORT".

![](https://i.gyazo.com/ba07638d957d098c501fa46da66f46aa.png)

**Comment by SPEN-CER** [comment]
You need to open the magic tab at least once, or did this still happen even after that?

**Comment by Sphiinx** [comment]
I did, but looking back on it now I think the bot got logged out and quickly logged back in before I noticed which caused this.

Thanks!

**Comment by SPEN-CER** [comment]
No problem, it'll be fixed with shadow-opening
