### ISSUE TITLE
The web tries to open the Varrock dig site gate without the requirements to do so

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#226]
![screen shot 2018-08-16 at 20 38 56](https://user-images.githubusercontent.com/13446008/44228091-ad541280-a194-11e8-8bfa-b87d8e0272ad.png)

It spams this gate to the dig site if you dont have the requirements.

This happened while web walking from varrock to Paterdomeus temple, where Drezel is.

**Comment by troy-lamerton** [comment]
After opening your quest list, RSPeer realises it doesn't have the requirements, and will stop trying to use this gate.
