### ISSUE TITLE
Add isInCutscene to api - Here is the varp

### ISSUE THREAD

**Issue by troys-code** [rs-peer/issues#230]
When you are not in a cutscene, the Varp `1021` == 0
When you are in a cutscene, the varp will change to another value.

It would be great to have this in the api as `boolean isInCutscene()`

This has held true for cutscenes in 3 quests. So I think it is universal to all cutscenes.

EDIT: It can also change to `2048` at the end of a cutscene.

I will update this list of varpbits and what they signify.

Cutscene varpbits:
When 542 and 4606 are both 1, you are in a cutscene.

* 542
* 4606

Others:

* 3756 - ?
* 4394 - ?
* 4605 -  this toggles when "Loading..." appears on the top left
* 5983 - level up chat dialog
* 6254 - ?
* 6363 - ?

**Comment by SPEN-CER** [comment]
542
3756
4394
4605
4606
5983
6254
6363

I'd need to know what each of these varpbits signify - if multiple relate to cutscenes or if only one of them does, as they all belong to varp 1021.
