### ISSUE TITLE
Item#isExchangeable returns some items which arent tradeable

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#232]

**Comment by SPEN-CER** [comment]
Need more info. Which items?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by Sphiinx** [comment]
?

**Comment by Man16** [comment]
Trying to solve issues from 1 year ago btw!!

**Comment by Sphiinx** [comment]
> Trying to solve issues from 1 year ago btw!!

?

**Comment by Man16** [comment]
> > Trying to solve issues from 1 year ago btw!!
> 
> ?

You're not cool man stop tryna fit in

**Comment by Sphiinx** [comment]
> > > Trying to solve issues from 1 year ago btw!!
> > 
> > 
> > ?
> 
> You're not cool man stop tryna fit in

Idk who u are
