### ISSUE TITLE
Interface interaction crashing issues.

### ISSUE THREAD

**Issue by Micrococonut** [rs-peer/issues#236]
I am creating a construction bot. When I interact with chat options for butlers or for the larder building space the client crashes like so https://ibb.co/cVfPtK. Sometimes it runs for 5 minutes, sometimes it runs for 20 seconds. It is very unlikely it's a problem with my code.

**Comment by Jasper-ketelaar** [comment]
What does your code for interacting with chat options look like?

**Comment by Micrococonut** [comment]
`        final InterfaceComponent chatbox = Interfaces.getComponent(219, 0);
        if(chatbox != null && chatbox.isVisible()) {
            if(chatbox.getComponent(0) != null && chatbox.getComponent(0).getText().equals("Really remove it?")) {
                final InterfaceComponent removePrompt = chatbox.getComponent(1);
                if(removePrompt != null && removePrompt.getText().equals("Yes")) {
                    Log.info("Yes");
                    removePrompt.click();
//                removePrompt.interact("Yes");
                    return 700;
                }
            }
            return 300;
        }

        final SceneObject larder = SceneObjects.getNearest("Larder");
        if(larder != null) {
            Log.info("Remove Larder");
            larder.interact("Remove");
            return 500;
        }
        return 400;
`

**Comment by Man16** [comment]
Use the Dialog class

**Comment by Jasper-ketelaar** [comment]
As Man16 said, use the Dialog class because what you're doing right now will indeed crash the game (trying to interact with dialog when it's already processing).

**Comment by SPEN-CER** [comment]
Or add a !Dialog.isProcessing() check, so it doesn't select an option when you've already selected one
