### ISSUE TITLE
[Suggestion] Add Inventory.getLast

### ISSUE THREAD

**Issue by RS-King** [rs-peer/issues#240]
Would be awesome to have an Inventory.getLast method similar, to get first. Super useful when using multiple items that take from the first available - you can just click last X times.

**Comment by troy-lamerton** [comment]
So for example, you could use the last bowstring on the last maple bow, and keep performing this action until you've strung all the bows?

**Comment by RS-King** [comment]
Exactly, I was thinking specifically for Fishing trawler: "spam" click  last bailing bucket in inventory or last filled bucket. It will start to fill / empty bucket #1, 2, 3, 4, etc.

**Comment by Jasper-ketelaar** [comment]
Added for next revision:
- Inventory.getLast(Predicate)
- Inventory.getLast(Pattern)
- Inventory.getLast(String...)
- Inventory.getLast(int...)

Thanks for the suggestion.
