### ISSUE TITLE
Trade.accept() or Players.getNearest("name").interact("Trade") does not work

### ISSUE THREAD

**Issue by buracc** [rs-peer/issues#241]
Tried "Follow" instead of "Trade", it worked. Something's up with trading.

**Comment by SPEN-CER** [comment]
Could you tell me what is logged when you enable the menu action debugger and trade a player?

**Comment by buracc** [comment]
[INFO] Fri Aug 24 01:06:02 CEST 2018: System: PathingEntityAction<PLAYER_ACTION_3>[index=4|name=xxx|x=3104|y=3274]

**Comment by SPEN-CER** [comment]
Trade.accept() is for the trade screen btw, not trade requests. I'll look into interact not working for trades though

**Comment by NeerOC** [comment]
Because the action isn't just "Trade"

**Comment by Blogans** [comment]
As pointed out by neer, the action is actually "Trade with" and not just "Trade"
