### ISSUE TITLE
Web gets stuck trying to walk to Port Khazard

### ISSUE THREAD

**Issue by RS-King** [rs-peer/issues#242]
If removed from Trawler, web walks in a circle trying to walk back to Port Khazard.

![image](https://user-images.githubusercontent.com/24397845/44904214-9c4ee980-acdc-11e8-9603-4e580f46b808.png)

**Comment by Sphiinx** [comment]
This is an issue with the Aucity webwalker that should be reported [here](https://github.com/ZachHerridge/Acuity/issues).

@SPEN-CER
