### ISSUE TITLE
Events don't de-register in the class inheriting from Script, if your script npe's once.

### ISSUE THREAD

**Issue by FrostySo** [rs-peer/issues#245]
Moral of the story, if your script seems to NPE even once, when you stop the script afterwards, you get bamboozled. The event won't de-register and will continue to stack if you run another instance of that script (and it NPE's again). I find it strange why it happens.

**Comment by SPEN-CER** [comment]
Seems to be fixed? Unable to reproduce

**Comment by FrostySo** [comment]
> Seems to be fixed? Unable to reproduce

Yea it's fixed now lol
