### ISSUE TITLE
 Movement.walkTo dungeon is broken. 

### ISSUE THREAD

**Issue by chadsisson** [rs-peer/issues#249]
Title. 
Cannot web walk to dungeons such as the following, 
3315, 9513, 0 (New Kalphite cave)
https://i.imgur.com/2FYD1qd.png
2879, 9811, 0 (Taverley Dungeon)
https://i.imgur.com/nbZNEYR.png
2786, 9996, 0 (Fremennik Slayer Dungeon)
https://i.imgur.com/tzyzm2d.png

**Comment by SPEN-CER** [comment]
The web does not support dungeons as of now
