### ISSUE TITLE
Webwalker goes 1 floorlevel too high

### ISSUE THREAD

**Issue by Vetoxication** [rs-peer/issues#250]
When using Movement#walkTo on a Position with floorlevel 2, it will walk to floorlevel 3 instead. The perfect example is in the Dark Warrior Fortress, where I want to walk to the 2nd floor but it goes to the third. 
`Movement.walkTo(new Position(3022,3626,2));`

**Comment by dQw4w9WgXcQ** [comment]
Old School RuneScape uses the British convention for floor numbering: Ground floor, first floor, etc.

**Comment by Vetoxication** [comment]
> Old School RuneScape uses the British convention for floor numbering: Ground floor, first floor, etc.

I know that. 0 is ground floor. However I need to get to floor 2. What happens if you execute that code, it will go to floor 3 and then go back to floor 2.
