### ISSUE TITLE
Players.getLocal().getTotalLevel() returns 0

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#255]
Players.getLocal().getTotalLevel() returns 0

**Comment by Sphiinx** [comment]
@SPEN-CER You implemented the workaround method `Skills.getTotalLevel()` so not sure if you want to close this now or eventually fix it?

**Comment by SPEN-CER** [comment]
This is supposed to work for other players too. The workaround is just for the local player.

**Comment by Lezor91** [comment]
Not actually a bug and is intended to work this way. The hook is also misnamed as total level as it has a more general purpose than just that. It is only sent by the server in certain areas where the total level or some form of skill level is needed to be drawn on a players right click menu. I'll probably deprecate this and add getSkillLevel to replace it along with some documentation to explain said "issue"
