### ISSUE TITLE
getHintArrowX() and getHintArrowZ() return incorrect values.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#256]
Game.getClient().getHintArrowX() and Game.getClient().getHintArrowZ() return incorrect values. This also leads to the HintArrow class returning incorrect values.

NOTE that the incorrect values may only be occurring for static hint arrow types.

Y returns the correct value, although X and Z return positive and negative numbers that are way larger than any actual position.

Please update the provider hooks for this as soon as possible as I use them for the majority of [SPX] Tutorial Island in which many users are waiting for a fix.

**Comment by SPEN-CER** [comment]
Fixed. The multipliers were broken.

**Comment by Sphiinx** [comment]
When will the next client update be that includes this?

**Comment by SPEN-CER** [comment]
No update, just restart your bot

**Comment by Sphiinx** [comment]
Awesome, thank you!
