### ISSUE TITLE
Deposit dialog not supported

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#259]
The Dialog class does not recognize deposit dialog as being dialog that is open, has options, or anything else.

![IMG](https://i.gyazo.com/116c631fedf09372d2f3b1122557109c.png)

**Comment by SPEN-CER** [comment]
Use EnterAmount

**Comment by SPEN-CER** [comment]
I will probably be deprecating it and replacing it with EnterInput or similar, as this was not made with text inputs in mind. I will not be merging it into Dialog.
