### ISSUE TITLE
Get dialog entered numbers.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#261]
Method to get the current user entered numbers in dialog could potentially be useful. For example, dialog that requires the user to enter a deposit amount. If the user has 999 entered in the dialog, the method would return 999 and so on. If I'm not mistaken, only numbers can be entered in these dialogs.

Dialog.getEntered();

**Comment by SPEN-CER** [comment]
I will add this when I replace EnterAmount with a new EnterInput class

**Comment by SPEN-CER** [comment]
Added EnterInput.getEntry for the next build, returns an empty string if the interface is not open
