### ISSUE TITLE
Varp Debugger ignore/target varp(s)

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#264]
Ability to ignore or target multiple specific varp(s) when using the Varp Debugger. It can be fairly tedious when trying to debug a several varps as you cannot specify more than one nor can you ignore specific or multiple varps.

The varp debugger can occasionally get spammed by other varps that you may not need to see at that moment where it can be difficult to debug the ones you do need.

![Example](https://streamable.com/s/go3oi/rfnedr)

**Comment by Jasper-ketelaar** [comment]
Added for next revision. Varp debugger now allows you to specify multiple by adding a , between multiple varps in the search box
