### ISSUE TITLE
Blast Furnace Bank Location/Deposit Box

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#265]
Blast Furnace bank location and deposit box needs to be added to the location enum for bank chests and deposit boxes. Please add these ASAP.

Bank Chest Information:
Chest position: (1948, 4956, 0)
ID: 26707
Actions: Use, Collect

Deposit Box Information:
Deposit box position: (1950, 4956, 0)
ID: 6948
Actions: Deposit

**Comment by Sphiinx** [comment]
@SPEN-CER Did you get a chance to fix this in RSPeer 1.29?
