### ISSUE TITLE
Client debug text font messed up

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#266]
Client debug text font seems to have changed to something different and slightly difficult to read.

![screen shot 2018-10-26 at 12 59 08 pm](https://user-images.githubusercontent.com/11341771/47587127-2b643080-d91f-11e8-9931-f64a82023be2.png)

**Comment by SPEN-CER** [comment]
Is this still the case?

**Comment by Sphiinx** [comment]
> 
> 
> Is this still the case?

Looks like it's fixed!

**Comment by Sphiinx** [comment]
@SPEN-CER Actually, it looks like it was fixed for the debugger text, but other client text still has this issue such as paint text, entity debugger, etc.
