### ISSUE TITLE
Closing the client opens a new client

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#267]
The first time the client is closed it will open a new client right afterward. This only happens the first time the client is closed but doesn't seem to occur if the second client is closed.

- Produced
RSPeer: v1.19
Launcher: Newest
O/S: macOS Mojave 10.14

**Comment by Sphiinx** [comment]
- Re-produced
RSPeer: v1.19
Launcher: Newest
O/S: Windows 10 Version 1803 (OS Build 17134.345)
