### ISSUE TITLE
Unable to start more than one client.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#268]
Unable to start more than a single client. Attempting to open a new client while one is already open will not do anything nor are any other processes started. This does not seem to be an instance issue as I have more than one instance and I'm not receiving any notifications.

- Produced
RSPeer: v1.19
Launcher: Newest
O/S: macOS Mojave 10.14

**Comment by Sphiinx** [comment]
- Unable to reproduce on Windows 10
RSPeer: v1.19
Launcher: Newest
O/S: Windows 10 Version 1803 (OS Build 17134.345)

**Comment by oNilian** [comment]
im getting the same issue :/ weird
