### ISSUE TITLE
Local scripts not being loaded/displayed

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#269]
Local scripts are not being loaded/displayed in the local script list when selecting which script to run. Building the artifacts into a jar or using the compiled class files does not make a difference.

- Produced
RSPeer: v1.19
Launcher: Newest
O/S: macOS Mojave 10.14

- Re-produced
RSPeer: v1.19
Launcher: Newest
O/S: Windows 10 Version 1803 (OS Build 17134.345)

**Comment by Sphiinx** [comment]
Looks to be an issue with the new Launcher that was released with v1.19. Downgrading to the previous launcher while on v1.19 resolves this issue.

**Comment by SPEN-CER** [comment]
Fixed
