### ISSUE TITLE
Forum doesn't send email notifications

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#272]
Forum doesn't send email notifications even when they are enabled.

Example: If the setting "When a new reply is posted in a topic you are watching" is set to "Notification & Email" it will only send a notification and not an email upon a new reply in a watched topic.

**Comment by Sphiinx** [comment]
Moved to the RSPeer API issues repo [here](https://github.com/MaddoxDevelopment/RSPeer-Api/issues/34).
