### ISSUE TITLE
Death listener triggered multiple times per death

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#285]
I tested with my own local player. Not sure with other sources.

**Comment by Blogans** [comment]
I've found it will proc more than once if you "die" more than once aka getting spec'd with something that'll cause 2 hitsplats in the same timeframe (or just more than 1 person killing you at the same time)

**Comment by SPEN-CER** [comment]
> 
> 
> I've found it will proc more than once if you "die" more than once aka getting spec'd with something that'll cause 2 hitsplats in the same timeframe (or just more than 1 person killing you at the same time)

This is likely to be the case.
