### ISSUE TITLE
RspeerEmail and RspeerPassword quickstart doesn't log in

### ISSUE THREAD

**Issue by josephmr** [rs-peer/issues#287]
On a fresh workstation (docker container/vm/etc) I tried to run the following:

`java -jar rspeer-launcher.jar config.json`

config.json (with sensitive info replaced):
```
{
        "RspeerEmail": "asdf@asdf.com",
        "RspeerPassword": "asdf",
        "Clients": [{
                "ScriptName": "Login",
                "IsRepoScript": false,
                "RsUsername": "asdf@asdf.com",
                "RsPassword": "asdf"
        }]
}
```

This leaves me at the rspeer login prompt screen. This can also be tested by deleting `$HOME/RSPeer`.

**Comment by Jasper-ketelaar** [comment]
Is "Login" an actual local script you have?
