### ISSUE TITLE
Add BankLocation.getNearestDepositable()

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#289]
Add BankLocation.getNearestDepositable(). This would be beneficial when attempting to get the nearest depositable location where you're not specifically trying to get a deposit box as a bank may be closer, but you also don't need a withdrawable bank as you're only depositing items.

**Comment by d-o-g** [comment]
arent they all depositable? `BankLocation.getNearest()`

**Comment by Sphiinx** [comment]
> arent they all depositable? `BankLocation.getNearest()`

Does that method include deposit boxes? The API doesn't have documentation on it.

**Comment by d-o-g** [comment]
it doesnt need documentation lol, i mean if theres a getNearestWithdrawable and other methods what would u expect getNearest to return

**Comment by SPEN-CER** [comment]
As mentioned, getNearest can include any BankLocation in its result
