### ISSUE TITLE
Piscatoris Bank Deposit Box

### ISSUE THREAD

**Issue by EvgeniBogdasarov** [rs-peer/issues#291]
The piscatorial bank deposit box is not working, here is the data:

Id = 29104
Action = Deposit
Position = 2330, 3686, 0,

**Comment by SPEN-CER** [comment]
I don't think that deposit box is even supported? I also do not want to add it, due to that particular deposit box being locked behind certain requirements - I'd need a reliable way to check if it is unlocked first, so I can filter it out where needed.

For the time being, just use SceneObjects
