### ISSUE TITLE
Position::isPositionWalkable returns incorrect value

### ISSUE THREAD

**Issue by DijkstraStar** [rs-peer/issues#293]
The predicate seems to return incorrect values. I don't know if if there are any other occurences but I stumbled upon a position in the lumbridge swamp mine for which it returns true even though the player is unable to walk there.

The exact location: (3322, 3146)

**Comment by SPEN-CER** [comment]
Are you sure that what you want is walkable and not isPositionInteractable?

**Comment by DijkstraStar** [comment]
> Are you sure that what you want is walkable and not isPositionInteractable?

Yes, I need to determine if the player can stand in the given location. 
Another incorrect return value: (3285, 3369)

**Comment by SPEN-CER** [comment]
isPositionInteractable
