### ISSUE TITLE
GameAccount not set before script starts

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#296]
RSPeer client doesn't set the game account before the script begins or even before onStart begins which leads to NPE's when attempting to use the GameAccount.

This only occurs the first time a script is started on a fresh client because after that the GameAccount is set and not null anymore. A good example would be my tutorial island script where it uses GameAccount in the onStart method to create the queue of accounts.

In order to reproduce it, start a fresh client and run a script with this in the onStart:
```java
@Override
    public void onStart() {
        System.out.println("GetAccount null: " + (getAccount() == null));
    }
````

Image:
![image](https://user-images.githubusercontent.com/11341771/51089989-a117b580-1732-11e9-866c-6a141dcfdd7f.png)

**Comment by SPEN-CER** [comment]
Fixed for the next build. 

Calling `GameCanvas.setInputEnabled(...)` in `onStart()` would also not work for the same reason, I've fixed this too.
