### ISSUE TITLE
RSItemDefinitions - getStackIds

### ISSUE THREAD

**Issue by Rhiel** [rs-peer/issues#309]
Can we get access to the stackIds and stackAmts getter?

**Comment by SPEN-CER** [comment]
What do you need these for?

**Comment by Rhiel** [comment]
For an inv api im working on:

`
 public boolean stacksWith(int id) {
        if (stackIds == null)
            return false;

        for (int stackId : this.stackIds) {
            if (stackId == id)
                return true;
        }
        return false;
    }
`

**Comment by SPEN-CER** [comment]
Added getVariantIds and getVariantStackSizes to RSItemDefinition for the next build
