### ISSUE TITLE
Worldhopper not working

### ISSUE THREAD

**Issue by DijkstraStar** [rs-peer/issues#312]
The following methods do not seem work if the worldhopper interface is not already open.

WorldHopper.randomHopInF2p();
WorldHopper.randomHopInP2p();

**Comment by Jasper-ketelaar** [comment]
Are you sure it's just these methods that don't work if the interace is not already open? Functionally they aren't different from any of the other hopping methods.

**Comment by DijkstraStar** [comment]
> Are you sure it's just these methods that don't work if the interace is not already open? Functionally they aren't different from any of the other hopping methods.

It could be that all methods are broken, Im just only using these though.

**Comment by SPEN-CER** [comment]
This is fixed for the next build already. https://github.com/rs-peer/issues/issues/310 addresses this

A temporary workaround is to open the world hopper interface which would cause the game to make the worlds available for the rspeer api.
