### ISSUE TITLE
Being returned to the credentials screen sometimes opens the world selector by accident

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#314]
E.g. when you logout, it will logout with the world selection screen open.

**Comment by SPEN-CER** [comment]
Are you using the default login handler? This already closes it for you

**Comment by Man16** [comment]
> Are you using the default login handler? This already closes it for you

Yes

**Comment by SPEN-CER** [comment]
Is it closing the world selector for you?

**Comment by Man16** [comment]
> Is it closing the world selector for you?

No

**Comment by SPEN-CER** [comment]
I've not been able to reproduce this. The login handler always activates and closes it for me
