### ISSUE TITLE
Quiver issues

### ISSUE THREAD

**Issue by DijkstraStar** [rs-peer/issues#317]
Sometimes when equipping an item (that does not go in the quiver slot) the quiver item slot will bug out and show the same item. This is not just visually but Equipment.getItems will also return the incorrect items.

The following screenshot shows the quiver holding a Blessed spirit shield. The script gui shows a list of items obtained from Equipment.getItems

https://gfycat.com/richbouncyauklet
another one:
https://gfycat.com/TatteredGrimDorado

**Comment by SPEN-CER** [comment]
This should be fixed in the next build, along with any other equipment issues.
