### ISSUE TITLE
Client Memory Leak

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#318]
When one or more clients are open, any clients that are running a script and are minimized suffer from a memory leak. Details including a JProfiler snapshot are included below.

At least one client must be open and the client must be running a script and the client window minimized. Upon the memory usage reaching the launch parameter specified memory, the CPU usage on the client skyrockets to about 60-70% where the client runs out of memory and the client crashes.

- Client Settings
  - Client 1.43
  - Everything default with logger expanded.
  - Launch Parameters `-Xmx384m -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Xss2m`

- System
  - Windows 10 Version 1803 (OS Build 17134.590)
  - Java 8 Update 201
  - Ryzen 7 1800x
  - 32GB Ram
  - GTX 1070TI

[JProfiler snapshot](https://github.com/rs-peer/issues/files/2910085/rspeer_memory_leak.zip)
[Streamable of the memory leak](https://streamable.com/09yw9)

![](https://i.imgur.com/0dBYfpT.png)

![](https://i.imgur.com/TgI5Dns.png)

**Comment by SPEN-CER** [comment]
Fixed. Thanks Mad & Sphiinx
