### ISSUE TITLE
Bank.open() stuck in Port Khazard

### ISSUE THREAD

**Issue by salmonmeister** [rs-peer/issues#319]
While using MadDev's AIO Miner I noticed I'd get stuck on walking back to the bank chest. It would just click around the area but never actually open the bank chest. Since [that bit of the code](https://gitlab.com/RsPeer/Open-Source-Scripts/blob/master/src/com/rspeer/MineHelper.java#L152) is really simple, I presume it's stuck on `Bank.open()`.

Related information on the bank chest at #237.

**Comment by SPEN-CER** [comment]
Closed as duplicate of https://github.com/rs-peer/issues/issues/242

**Comment by rubenvereecken** [comment]
I should add, as it might give you a bit more insights into the issue, that whereas in #242 it got stuck somewhere far from Port Khazard, in my case it actually walked to the Port Khazard chest then got stuck in front of that.
