### ISSUE TITLE
PlayerAppearance.getEquipmentIds() returns incorrect values

### ISSUE THREAD

**Issue by DDLC** [rs-peer/issues#325]
Expected output (taken with another bot client): https://i.imgur.com/h4Lr4Rk.png

Actual output (from looping through the equipment ids): 

[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1681
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 0
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 2237
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1365
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1613
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 0
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 283
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1611
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 0
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1577
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 1573
[INFO] Fri Mar 22 18:45:29 EDT 2019: Info: 367

**Comment by itsAsta** [comment]
You need to minus 512 from the Item ID.
E.g. 2237 - 512 = 1725
1725 gives you Amulet of strength etc.

**Comment by SPEN-CER** [comment]
What Asta said.
