### ISSUE TITLE
[Suggestion - Bot Panel] Make script name clickable to direct to script thread.

### ISSUE THREAD

**Issue by ItsCavero** [rs-peer/issues#327]
There isn't an easy way to visit your script thread.
To do so, make the script name inside the dashboard clickable to direct you to the script thread, see picture posted.
![JEGmRDW](https://user-images.githubusercontent.com/48846804/56004195-df852800-5cc1-11e9-9eeb-d585a8da0a56.png)

**Comment by SPEN-CER** [comment]
Probably belongs here https://github.com/MaddoxDevelopment/RSPeer-Api/issues

**Comment by ItsAsta** [comment]
@SPEN-CER I've opened one there mb
