### ISSUE TITLE
Web walker and fairy ring DJR

### ISSUE THREAD

**Issue by rhonium** [rs-peer/issues#331]
When using the webwalker if it has to use the fairy ring DJR it properly spins it to DJR but doesnt click on teleport

**Comment by SPEN-CER** [comment]
Does this only happen with DJR? 

Can you enable the menu action debugger and click the teleport button manually? Please post whatever is logged

**Comment by rhonium** [comment]
Yes only with DJR

[INFO] Fri Apr 19 13:04:41 EDT 2019: Info: ObjectAction<OBJECT_ACTION_1>[id=29495|x=2644|y=3495]

[INFO] Fri Apr 19 13:04:44 EDT 2019: Info: ComponentAction<INTERFACE_ACTION>[actionIndex=1|componentUid=26083347|componentGroup=398|componentIndex=19]

[INFO] Fri Apr 19 13:04:44 EDT 2019: Info: ComponentAction<INTERFACE_ACTION>[actionIndex=1|componentUid=26083350|componentGroup=398|componentIndex=22]

[INFO] Fri Apr 19 13:04:45 EDT 2019: Info: ComponentAction<INTERFACE_ACTION>[actionIndex=1|componentUid=26083351|componentGroup=398|componentIndex=23]

[INFO] Fri Apr 19 13:04:46 EDT 2019: Info: ComponentAction<INTERFACE_ACTION>[actionIndex=1|componentUid=26083351|componentGroup=398|componentIndex=23]

//stuck here then i clicked

[INFO] Fri Apr 19 13:04:55 EDT 2019: Info: ComponentAction<INTERFACE_ACTION>[actionIndex=1|componentUid=26083354|componentGroup=398|componentIndex=26]

**Comment by SPEN-CER** [comment]
https://i.imgur.com/uyyhBH7.png Oops lol fixed for the next build
