### ISSUE TITLE
ScenePosition uses base x for both base x and base y args

### ISSUE THREAD

**Issue by Janca** [rs-peer/issues#333]
https://i.imgur.com/wicBn1I.png

The secondary constructor for ScenePosition passes base x for both base x and base y arguments.

**Comment by mcscrad** [comment]
where did you find this code?

**Comment by Sphiinx** [comment]
> where did you find this code?

You can see it if you open the decompiled files. The constructor in the ScenePosition class does not get obfuscated by allatori.
