### ISSUE TITLE
RSTile.getSceneY() returns MASSIVE number

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#335]
```
RSTile[][][] tiles = Game.getClient().getSceneGraph().getTiles();
tiles[0][0][0].getSceneX(); => 78
tiles[0][0][0].getSceneY(); => 1368526647
```

it seems the sceneX returns normal scene numbers.

**Comment by Hawksian** [comment]
Appears to be a broken hook multiplier! 

What are you using this method for btw?

**Comment by yawhide** [comment]
Checking if an RSTile has line of sight to another RSTile

**Comment by mcscrad** [comment]
Check if an RSTile has like of sight to another RSTile (the rstiles are from the player and an NPC respectively)

**Comment by Hawksian** [comment]
Why are you using RSTile for this?

**Comment by Hawksian** [comment]
Why are you using RSTile in the first place though?

**Comment by mcscrad** [comment]
```
RSTile[][][] tiles = Game.getClient().getSceneArea().getTiles();
int x = tiles[Game.getClient().getFloorLevel()][0][0].getSceneX();
int y = tiles[Game.getClient().getFloorLevel()][0][0].getSceneY();
CollisionData[] collisionDate = Game.getClient().RSCollisionMap(); // this has scene coordinates
// insert mathy stuff here
...
collisionDataFlags[x][y] <--- y is a HUGE number and i get an "index out of bounds" error.
```

**Comment by Hawksian** [comment]
That doesn't answer my question..

**Comment by mcscrad** [comment]
> That doesn't answer my question..

that is why I am using it? `getSceneGraph` returns RSTiles

**Comment by Hawksian** [comment]
And why are you using getSceneGraph for this? Instead of the standard getPosition etc

**Comment by mcscrad** [comment]
> And why are you using getSceneGraph for this? Instead of the standard getPosition etc

I dont think the Position class has a way for me to get all the scene `positions` in the Player.getLocal() area.

**Comment by Hawksian** [comment]
If you want every position then loop 0-103 x and y and 0-3 z. You don't need to use RSTile.getSceneX/getSceneY at all

**Comment by Hawksian** [comment]
Sure you can pm me on Discord if you need: Hawkeye#7699
