### ISSUE TITLE
Npc.getTarget().getName() has extra trailing whitespace

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#336]
```
for (Npc n: Npcs.getLoaded())
        {
            var target = n.getTarget();
            if (target != null)
            {
                Log.info("'" + target.getName(), "', '" + Players.getLocal().getName() + "'");
            }
        }
```
the output looks like `'Hello    ', 'Hello'`

**Comment by mcscrad** [comment]
oh, and `target.getName.trim()` isnt removing the extra whitespace

**Comment by SPEN-CER** [comment]
Which npc does this occur on?

**Comment by mcscrad** [comment]
> Which npc does this occur on?
> 
> Edit: nvm misread. Is your rsn 1 word?

it is, its similar to `MonkeyFace` (as in, the display name in game is in PascalCase)
