### ISSUE TITLE
toString()

### ISSUE THREAD

**Issue by Janca** [rs-peer/issues#337]
Can we get `toString()` method added to Player, Npc, SceneObject and Pickable. Preferably name, id, and position.

**Comment by Sphiinx** [comment]
For what reason? Can't you just specify the interactable and then call those methods on it to print any details you want?

**Comment by Eclipseop** [comment]
> For what reason? Can't you just specify the interactable and then call those methods on it to print any details you want?

xddddddddddd
Obviously yes you can, but having a toString takes 2 seconds and if it provides meaningful data for debugging purposes without having to call 3 methods to obtain it, im all for it.

**Comment by SPEN-CER** [comment]
Added
