### ISSUE TITLE
Game.getClient().getTickCount()

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#338]
I want to be able to get the tick count instead of relying on me counting myself.

**Comment by SPEN-CER** [comment]
Why do you need to count them?

**Comment by mcscrad** [comment]
> Why do you need to count them?

to keep track of projectiles and when they will hit me. it is handy to record when the projectile fires and count the ticks for when they hit the player.

**Comment by SPEN-CER** [comment]
You can use Projectile.getStartCycle and getEndCycle?

**Comment by yawhide** [comment]
Do those give back tick counts? All I know is they give back ints.

Any other use case, I want to count how many ticks between some actions.monster attacking, or fishing or w.e

**Comment by mcscrad** [comment]
Do those give back tick counts? All I know is they give back ints.

Any other use case, I want to count how many ticks between some actions.monster attacking, or fishing or w.e

**Comment by mcscrad** [comment]
now i know nothing, so take this with a grain of salt, but in other clients (like runelite), it seems that getting the tickcount is just a hook we need to listen for

https://github.com/runelite/runelite/blob/3ce7a328843e0babc022de7a2a6b39d50ff7464f/runelite-client/src/main/java/net/runelite/client/callback/Hooks.java#L145

**Comment by SPEN-CER** [comment]
It's just a matter of doing tick++ in the TickListener lol

**Comment by mcscrad** [comment]
> It's just a matter of doing tick++ in the TickListener lol

i am doing that but how do I know that the client wont have a duplicate event?

**Comment by SPEN-CER** [comment]
it won't
