### ISSUE TITLE
Method for clicking minigame tab sub-tabs.

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#339]
Jagex changed the minigame tab so now there are sub-tabs. A method for clicking minigame tab sub-tabs would be useful as the content in them is not loaded unless they're selected.

![](https://cdn.discordapp.com/attachments/382525963298406410/573042475590221834/unknown.png)

**Comment by SPEN-CER** [comment]
Why do you need to open subtabs? 

What content specifically do you need to be loaded?

**Comment by Sphiinx** [comment]
> Why do you need to open subtabs?
> 
> What content specifically do you need to be loaded?
> 
> This was the case prior to the tab changes too

In order to collect which quests have been completed the quest sub-tab needs to be the selected sub-tab.

**Comment by SPEN-CER** [comment]
As far as quests go, even if the sub tab is not loaded you still have to open the tab itself to update the text colors (this was always the case even prior to the subtab changes). 

I have no plans to add this, but as far as quests go, there will be an api for them soon (which doesn't require text colors to be loaded)
