### ISSUE TITLE
Game.getEngineCycle() returns a number very different than ProjectileMoveEvent.getStartCycle()

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#341]
ProjectileMoveEvents have a method called `getStartCycle()`.
Now i want to know that a projectile has "happened" only once (and i can do this by comparing the `getStartCycle()` is  <= something)

what is that something method? is it method in the `Game` class?
the only method i can see in the `Game` class is `getEngineCycle()` but in my testing, that returned `348048`
and `getStartCycle()` returned `957390302` (these two numbers arent even close haha)

**Comment by mcscrad** [comment]
Is there anymore info you might need? @SPEN-CER

**Comment by SPEN-CER** [comment]
Closing for #359
