### ISSUE TITLE
Cooking Karambwans doesn't work

### ISSUE THREAD

**Issue by samspeake** [rs-peer/issues#342]
Using the Production class, the Keyboard class, and the Interface class, you can't hit the 2/Cooked Karambwan option most of the time. It'll hit the button but nothing will happen, and randomly sometimes it'll work. https://gyazo.com/023550e9fc018438576c3c398b45291e

**Comment by SPEN-CER** [comment]
Show code

**Comment by samspeake** [comment]
https://gist.github.com/samspeake/b53e6284a32f62d1eb5adddbf9c60c01

I have tried every way to do this that we could think of in the development
channel, they all get the same issue.

**Comment by SPEN-CER** [comment]
Does Production.initiate(1) yield the same result?

**Comment by samspeake** [comment]
I’m on my phone away from my computer so I can’t remember which opcode is
which, but I’m pretty sure Production.initiate(opcode for option 1) worked
to cook Poisoned karambwans, but Production.initiate(opcode for option 2)
did not work to cook Cooked karambwans.

**Comment by SPEN-CER** [comment]
That is very strange, if you are able to lend me an account I can have a look tomorrow

**Comment by samspeake** [comment]
I only have one account with the cooking level and quest done which is a
pretty valuable account to me. It just requires decent cooking and the
completion of Tai Bwo Wannai Trio. If you can’t find another, though, let
me know.
