### ISSUE TITLE
ProjectileMoveEvent.getTargetPosition() incorrect

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#343]
Hello,

I found a bug in ProjectileMoveEvent.getTargetPosition(). It's Y coord is off by _a lot_.
the `getPosition()` method is returning the correct coord

Here is my example, on the left is projectileMoveEvent.getTargetPosition() and on the right is projectileMoveEvent.getPosition():
```
// .getTargetPosition()                     .getPosition()
Position[x=2122, y=2115, level=0], Position[x=2122, y=5659, level=0]
```

here is another example:
```
targetPos() Position[x=2113, y=2112, level=0], getPos() Position[x=2112, y=5655, level=0] 
```

here is another example
```
targetPos() Position[x=2105, y=2107, level=0], getPos() Position[x=2104, y=5644, level=0]. ScenePosition[x=49, y=-3485, level=0], ScenePosition[x=48, y=52, level=0] 
```

**Comment by mcscrad** [comment]
Is there anymore info you might need? @SPEN-CER

**Comment by SPEN-CER** [comment]
fixed for next build
