### ISSUE TITLE
Include gnome stronghold banks in the tree

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#344]
thanks

### south
GNOME_STRONGHOLD_TREE_SOUTH
Name: "Bank booth"
Action: "Bank"
Positions: new Position(2448, 3481, 1), new Position(2449, 3481, 1), new Position(2450, 3481, 1)
Conditions: Members
Type: BankLocation.Type.BANK_BOOTH

GNOME_STRONGHOLD_TREE_NPC_SOUTH
Name: "Gnome banker"
Action: "Bank"
Positions: new Position(2448, 3480, 1), new Position(2450, 3480, 1)
Conditions: Members
Type: BankLocation.Type.NPC

### west 
GNOME_STRONGHOLD_TREE_WEST
Name: "Bank booth"
Action: "Bank"
Positions: new Position(2441, 3487, 1), new Position(2441, 3488, 1), new Position(2441, 3489, 1)
Conditions: Members
Type: BankLocation.Type.BANK_BOOTH

GNOME_STRONGHOLD_TREE_NPC_SOUTH
Name: "Gnome banker"
Action: "Bank"
Positions: new Position(2440, 3488, 1)
Conditions: Members
Type: BankLocation.Type.NPC

**Comment by SPEN-CER** [comment]
Added west and south booths
