### ISSUE TITLE
Prayers.isUnlocked(Prayer.RIGOUR) returns true even if you haven't bought the scroll to unlock it

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#346]
title ^

**Comment by buracc** [comment]
isUnlocked checks if the prayer icon is unlocked, not if the scroll has been used. Simply add a toggle to ur script for users if they want to use rigour/augury.

**Comment by Gengsta** [comment]
> 
> 
> isUnlocked checks if the prayer icon is unlocked, not if the scroll has been used. Simply add a toggle to ur script for users if they want to use rigour/augury.

This was discussed yesterday and it is actually supposed to tell if it's unlocked (used scroll) or not, but no one has supplied whatever tells if it is. (varp?)

**Comment by buracc** [comment]
> y

There is no varp for it.

**Comment by SPEN-CER** [comment]
fixed for the next build
