### ISSUE TITLE
Movement.getDestinationDistance() returns HUGE number when within "3" of destination tile

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#347]
https://vimeo.com/336931126

**Comment by mcscrad** [comment]
I think Movement.getDestination() is also fucked up, returns weird ass numbers (maybe that is the root cause)

**Comment by mcscrad** [comment]
I think i know the issue, Movement.getDesintation() becomes null when you are withing 3 tiles (sometimes its within 2 or 1 tiles of the destinition)

**Comment by 2baad4u2** [comment]
It returns that "weird ass number" because at that moment the destination is null. You should be checking Movement.isDestinationSet() before using getDestinationDistance()
