### ISSUE TITLE
Enchanced scripter panel on website

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#35]
I want to see who has got my script added at a minimum.

Other stuff such as unique runs per day would be interesting stats.

**Comment by Man16** [comment]
Exposing the user is fine.

Maybe something we can look to in the future once everything is in place for a better scripter panel.

**Comment by Sphiinx** [comment]
@SPEN-CER This can probably be closed since it should be on the[ RSPeer API issues](https://github.com/MaddoxDevelopment/RSPeer-Api/issues).
