### ISSUE TITLE
Magic.canCast() returns true if you have the runes but are not on the right spellbook

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#351]
I was on ancients, but I had the runes for high alchemy. `Magic.canCast(Spell.Modern.HIGH_LEVEL_ALCHEMY)` returned true

**Comment by SPEN-CER** [comment]
Fixed for the next build.

Alongside this, I've deprecated Magic.SPELLBOOK_* constants and Magic.getSpellBook(), the new replacement is constants in the Magic.Book enum & Magic.getBook()
