### ISSUE TITLE
add hosidius cooking range bank chest

### ISSUE THREAD

**Issue by mcscrad** [rs-peer/issues#354]
HOSIDIUS_COOKING_RANGE
Name: "Bank chest"
Action: "Use"
Positions: new Position(1675, 3615, 0)
Conditions: Members
Type: BankLocation.Type.BANK_CHEST

**Comment by SPEN-CER** [comment]
Which one is this, the one in the hosidius house? The BankLocation enum already has 3 hosidius banks (mess hall, vinery, hosidius house), all of which I imagine needs changing after the last game update

**Comment by yawhide** [comment]
This is the one with ramoean (it's got a range that gives you bonus burn rate success)

**Comment by mcscrad** [comment]
It's the one where the range makes it extra hard to burn food. There is an npc called ramocean

**Comment by SPEN-CER** [comment]
Ah so the one next to the mess hall. Updated, I'll change the rest for the next build too thanks for the report
