### ISSUE TITLE
[Suggestion] Change the title of RSPeer to "RSPeer - Instance Limit Reached" if the instance limit is reached

### ISSUE THREAD

**Issue by DDLC** [rs-peer/issues#355]
I use a custom bot launching program that scans the titles of open clients to help me detect certain errors (i.e. non-working proxy will cause the title to be "RSPeer - null", which will make my bot launcher choose another random proxy for that bot and reload it). However, there is currently no way to detect whether I have reached the instance limit by checking attributes of the client (i.e. the title) with another program.

**Comment by MaddoxDevelopment** [comment]
This should be resolved now that the client auto closes if the limit is reached.
