### ISSUE TITLE
"Instance Limit" error even when I have unlimited instances

### ISSUE THREAD

**Issue by DDLC** [rs-peer/issues#356]
I upgraded to unlimited instances last night, but I'm occasionally getting instance limit errors when launching bots when I'm running close to 60 bots at once, which was close to what my instance limit was before I upgraded.

Steps to reproduce bug:
-I normally have 58 clients running
-I launch 5 tutorial island bots
-Sometimes, one or two of them will have the instance limit error

**Comment by MaddoxDevelopment** [comment]
This should be fixed now that instance tracking does not happen upon startup anymore.
