### ISSUE TITLE
Incorrect varbits for farming

### ISSUE THREAD

**Issue by chadsisson** [rs-peer/issues#358]
RSpeer is saying dead watermelons is varbit 5 but the correct varbit is 248 as per runelite client and previous testing. 
Testing was done with catherby south allotment patch. 
https://i.imgur.com/AeAYSyk.png

**Comment by SPEN-CER** [comment]
Very unlikely

Show code

**Comment by chadsisson** [comment]
Im a stoopid fuck, issue on my end.
