### ISSUE TITLE
Minigames.teleport() and Tabs.open(QUEST_LIST) are broken.

### ISSUE THREAD

**Issue by adivorcedfork** [rs-peer/issues#364]
Minigames.teleport() seems to be broken. Also Tabs.open(QUEST_LIST) is broken (corresponding to the new minigames tab.)

**Comment by SPEN-CER** [comment]
Opening the tab works fine?

There does seem to be an issue with teleport, looking into it now

**Comment by adivorcedfork** [comment]
Ya tested the tab today and it was working fine. Forget what I was doing to cause the issue yesterday. But yeah, Minigames.teleport() seems to select the correct minigame but not click teleport.

**Comment by SPEN-CER** [comment]
Yes I've fixed that for the next build.
