### ISSUE TITLE
Prayers.toggleQuickPrayer not working as intended

### ISSUE THREAD

**Issue by frannytheman** [rs-peer/issues#365]
toggleQuickPrayer sometimes opens up the quick prayer setup and for whatever reason can no longer be used for prayer flicking even though it could be just a couple of weeks ago (could be because of a built in sleep). I'll show a gif of prayer flicking with the exact same code except one uses toggleQuickPrayer and the other uses the interface.

Prayer flicking using toggleQuickPrayer
https://imgur.com/Zd1aXzj (notice it opens up setup at end of gif and doesn't keep prayer toggled)

Prayer flicking using interface
https://imgur.com/69ZWI5C (keeps prayer toggled, no opening of setup, works as intended)

**Comment by SPEN-CER** [comment]
fixed for next build
