### ISSUE TITLE
getOrientation() on sceneObject not working properly

### ISSUE THREAD

**Issue by SilenceP44** [rs-peer/issues#369]
For example:
getOrientation() returns 0 for the following 2 sceneObjects (staircases) in ardounge while they don't have the same rotation:
https://cdn.discordapp.com/attachments/224618433860468737/589186829597671571/unknown.png
https://media.discordapp.net/attachments/382525963298406410/588829584581984391/unknown.png

note: These objects have the same id.

**Comment by SPEN-CER** [comment]
Are you using this to calculate object areas?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by Jasper-ketelaar** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by buracc** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by Sphiinx** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?
