### ISSUE TITLE
GrandExchange.open() doesn't work on certain tile(s).

### ISSUE THREAD

**Issue by SilenceP44** [rs-peer/issues#370]
When using GrandExchange.open() while standing on the following tile, the bot does not open the Grandexchange.

Standing on this square happens quite alot if you switch between banking and using ge in your script.

https://cdn.discordapp.com/attachments/224618433860468737/589223738747256852/unknown.png

**Comment by SPEN-CER** [comment]
thanks for the report, fixed for the next build

**Comment by SilenceP44** [comment]
Still doesn't work properly. Same issue is present in v1.84

**Comment by Jasper-ketelaar** [comment]
If you manually interact with the Grand Exchange dude from that tile, does it also not work?

**Comment by TheHolyWaffle** [comment]
Can confirm, it doesn't work. Took a screenshot of the example tile in question: 
![image](https://user-images.githubusercontent.com/787914/60046673-321e8f80-96c8-11e9-8928-f16d7a1ec6a8.png)

Interacting manually with the Clerk does work, so it's an rspeer issue.

**Comment by SPEN-CER** [comment]
Fixed for the next build
