### ISSUE TITLE
Projection garbage

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#371]
Projection for some reason has a lot of garbage renders if there are multiple tiles and it gets worse the more there is/further out they are. The zoom is set to default.

In the videos, you can see that when I look at a certain angle you can see all the lines going to specific points at N, E, S, W

This happens with Projection and outline.
10 Tiles
Video of what's happening: https://streamable.com/zpnrj
![](https://i.imgur.com/3dHToc6.png)

25 Tiles
Video of what's happening: https://streamable.com/snpve
![](https://i.imgur.com/udHwkwR.png)

**Comment by Jasper-ketelaar** [comment]
Yeah, our projection methods aren't perfect. We don't feel like fixing these at least for now though as the client doesn't require an accurate projection for any functionality except for rendering (which never limits script capabilities). Perhaps in the future, when there are less essential matters at hand, we will take a look at these functions.

**Comment by Sphiinx** [comment]
@Jasper-ketelaar Why not leave this open until it can be taken care of then? I use this for visualizing region and collision data.

I don’t see a point in closing the issue as others will probably report it as well. Just leave it open until someone can take care of it lol

**Comment by Jasper-ketelaar** [comment]
Didn't mean to close.

**Comment by SPEN-CER** [comment]
Fixed https://i.imgur.com/8FtkPp6.jpg
