### ISSUE TITLE
Login blocking event doesn't stop script when RS updates

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#373]

**Comment by SPEN-CER** [comment]
Are you sure you're not overriding it? If not then they either changed the response code for update or we have it incorrect

**Comment by Jasper-ketelaar** [comment]
Seems like they've added a new response code that also indicates a Runescape update. Not sure why there are two different response codes both indicating the exact same thing? Added a new LoginResponseEvent and made the bot stop on that response event now also.
