### ISSUE TITLE
Request - Add isFacing

### ISSUE THREAD

**Issue by AshGreh** [rs-peer/issues#374]
It would be nice to know if i'm facing an Npc or SceneObject or if another player is facing a SceneObject.

**Comment by Jasper-ketelaar** [comment]
When should the player be considered to be facing the SceneObject though? Only when there is a straight line between the object and the player and the player is facing that direction? What about when an object is on the diagonal towards the north-west direction and the player is facing west? 

I'm down to implement this feature but a use case or more descriptive request would be appreciated.

**Comment by AshGreh** [comment]
A straight line between the entities would make sense for what I was asking. For example, while woodcutting, the player turns towards the tree they want to interact just before the actual interaction, forming a straight line between them and the tree.

**Comment by Jasper-ketelaar** [comment]
Yeah, but here you're assuming the tree is already on the same line as one of the directions the player can face. If the tree is not on the same line as one of the 8 directions a player could face, what do you think the method should return?

**Comment by AshGreh** [comment]
Hey, sorry for the delayed reply. I missed the notification. Yeah, I see the flaw in my request. I'm guessing it would be better if is facing is able to tell if you're facing towards an entity a tile away using the 8 directions. Anything else would be too much trouble and would result in more confusion. I wanted something similar to http://forums.rspeer.org/topic/760/find-sceneobject-interacting-with-count-players-trying-to-interact-with-the-same-sceneobject to figure out the count of players interacting with the entity, but also for npcs.

**Comment by Jasper-ketelaar** [comment]
Alright, I'm assuming you only want to check within 1 tile from the entity and not any bigger range?

**Comment by AshGreh** [comment]
Yes, that's right.

**Comment by SPEN-CER** [comment]
I feel that adding a Direction getDirection to Entity would suffice. You can use methods offered in Direction for anything additional

**Comment by AshGreh** [comment]
I'm in support of Direction#GetDirection but eventually, people would write isFacing anyway. So why not do both Spencer?

**Comment by Jasper-ketelaar** [comment]
I'm down to add both methods.

**Comment by AshGreh** [comment]
Thank you!

**Comment by Jasper-ketelaar** [comment]
Added `PathingEntity#getDirection()` and `PathingEntity#isFacing(Positionable)` for next version.
