### ISSUE TITLE
World hopper doesnt click anymore on the "In the future only warn me about dangerous worlds" warning

### ISSUE THREAD

**Issue by desert1989** [rs-peer/issues#375]

**Comment by Jasper-ketelaar** [comment]
Could you provide a code snippet in which this happens? I just tested it locally and it worked fine.

**Comment by desert1989** [comment]
Today it works again. I really dont know why.

**Comment by SPEN-CER** [comment]
Are you sure it wasn't just an issue on your end?

**Comment by desert1989** [comment]
Yeah, i think it must be.
