### ISSUE TITLE
PredefinedPath not walking on defined positions

### ISSUE THREAD

**Issue by ItsCavero** [rs-peer/issues#377]
Seems like it's generating positions to walk on by itself, instead of using the positions from the array. As if it was using Movement.walkTo();

Also stops randomly at some Position and won't work ever again.

**Comment by Jasper-ketelaar** [comment]
PredefinedPath builds a subpath between the player and the currently furthest reachable tile and then uses this path to walk. So yes, PredefinedPath is generating positions to walk on by itself.

**Comment by ItsAsta** [comment]
So there isn't a way to walk our selected path, besides writing our own method then, correct?

**Comment by frannytheman** [comment]
I believe it breaks when it gets to a tile and hasnt loaded in the next tile yet. Best to make the positions extremely close together if you run into this issue

**Comment by Jasper-ketelaar** [comment]
For the next RSPeer version, I have added a variable in PredefinedPath `buildSubPaths`. When this is set to false the walk function won't build a subpath between the current location and the furthest tile, and will instead just set the walk flag to the furthest tile. All you have to do is disable building subpaths when building your PredefinedPath like such: 

`
PredefinedPath exact = PredefinedPath.build(tiles...).withBuildSubPaths(false);
`
