### ISSUE TITLE
Definition classes to impl Identifiable

### ISSUE THREAD

**Issue by Janca** [rs-peer/issues#378]
Can the `RSDefinition` class also extend Identifiable for the methods `getId` and `getName` for use in generics like `Predicate<Identifiable>`. Thaaaanks

**Comment by Jasper-ketelaar** [comment]
I'm pretty sure none of our other injection interfaces implements Identifiable. Can you give some more info as to where you plan to use RSDefinition generically with other types?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by buracc** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by Sphiinx** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by SPEN-CER** [comment]
?
