### ISSUE TITLE
Prayers.flick sometimes keeps the target prayer on

### ISSUE THREAD

**Issue by Typiqally** [rs-peer/issues#381]
`Prayers.flick(Prayer.PROTECT_FROM_MAGIC, Random.high(500, 550));` will sometimes keep the prayer enabled after flicking it on.

**Comment by Jasper-ketelaar** [comment]
This is probably due to server lag. If you wait between 500 and 550 ms, which is less than a server tick, and you miss a server tick the prayer won't properly deactivate. Are you trying to 1t flick? If so, you should take into account the response time of the server in your delay.

**Comment by SPEN-CER** [comment]
Utilise TickListener if this is the case
