### ISSUE TITLE
Item.IsExchangeable() bug for noted items after last update

### ISSUE THREAD

**Issue by aids9345435345** [rs-peer/issues#382]
(returns false for noted items even if theyre exchangeable)

for(Item i : Inventory.getItems()) {
Log.info("exchangeable?: "+ i.isExchangeable() + " itemid: "+ i.getId());
}
[04:20:11] Info exchangeable?: false itemid: 1276
[04:20:11] Info exchangeable?: false itemid: 330
[04:20:11] Info exchangeable?: false itemid: 1162

**Comment by Jasper-ketelaar** [comment]
Are you sure this isn't standard behaviour? I remember noted items weren't considered exchangeable whereas their unnoted versions were.

**Comment by SPEN-CER** [comment]
> 
> 
> Are you sure this isn't standard behaviour? I remember noted items weren't considered exchangeable whereas their unnoted versions were.

Item#isExchangeable checks exchangeable on the unnoted variant

**Comment by aids9345435345** [comment]
> Are you sure this isn't standard behaviour? I remember noted items weren't considered exchangeable whereas their unnoted versions were.

It wasn't standard as it broke a script of mine on the update before last.

**Comment by Jasper-ketelaar** [comment]
Does it not work for any item any longer or just those specific items?

**Comment by Jasper-ketelaar** [comment]
?

**Comment by buracc** [comment]
?

**Comment by SPEN-CER** [comment]
?

**Comment by aids9345435345** [comment]
looks like it's fixed
nubs
