### ISSUE TITLE
Missing bank location

### ISSUE THREAD

**Issue by DijkstraStar** [rs-peer/issues#384]
The motherlode mine bank chest is missing from the BankLocation enum.

Position: (3761, 5666, 0)
Type: Bank chest
Action: Use

**Comment by SPEN-CER** [comment]
What are the requirements to enter the motherlode mine?

**Comment by Gengsta** [comment]
You only need a pickaxe to get to the "inner circle" where the bank is afaik

**Comment by SPEN-CER** [comment]
Wiki states "At least 30 Mining is required to mine on the lower level". Do you know if this is just a requirement to mine or is it also a requirement to enter?

**Comment by ForsakenWaRp** [comment]
You need 30 Mining to enter.

**Comment by Caztro** [comment]
No you don't. you can enter at any level.
https://i.imgur.com/kM1DyEz.png

**Comment by SPEN-CER** [comment]
Added for the next build
