### ISSUE TITLE
Run is always toggled on

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#387]
If running was toggled programmatically it sometimes never gets turned off, even if the button doesn't appear as if it's turned on (even if you try to toggle it on/off manually) which causes the run energy to always be 0 whenever moving/interacting.

https://www.zaiat.com/upload/mtlfan12.png

**Comment by MzScorpio** [comment]
To clarify further,
- If I walk to a tile while energy is 0, then it goes higher, my character will not run.
- If I walk to a tile while energy is above 0, my character will run.

Same goes for interacting

**Comment by MzScorpio** [comment]
Also, this is occurring without having a script running.

**Comment by SPEN-CER** [comment]
are you sure you're not holding ctrl down?

**Comment by MzScorpio** [comment]
> 
> 
> are you sure you're not holding ctrl down?

It seems that it fixed itself now; and no I was never holding ctrl down, nor did I press it at any given moment.

**Comment by SPEN-CER** [comment]
Did you have sticky keys enabled?

**Comment by MzScorpio** [comment]
Nope, disabled

**Comment by MzScorpio** [comment]
I could've probably hit ctrl and it never registered a release in the applet's listener
