### ISSUE TITLE
Players.getLocal().getTarget() does not return null after world hop.

### ISSUE THREAD

**Issue by Eligeion** [rs-peer/issues#389]
If you hop worlds while in combat (safe spotting) Players.getLocal().getTarget() continues to return old target despite not being in combat.

**Comment by Jasper-ketelaar** [comment]
Are you sure the player instance you're getting the target from is the new, relogged player?

**Comment by Eligeion** [comment]
That would do it. I'm misunderstanding how Game.STATE_HOPPING_WORLD works, since it doesn't redefine "me" after world hops. 

Thank you.
