### ISSUE TITLE
All "walk" methods get stuck in lumy castle

### ISSUE THREAD

**Issue by ZanSpehonja** [rs-peer/issues#391]
The Movement.walkToRandomized(Position)
       Movement.walkTo(Position)
       HpaPath.build(Position).walk()
       Bresenham.build(Position).walk()
       PredefinedPath.build(Position).walk()

All return false when right next to stairs in the first floor of lumbridge castle; when the next step would be going down the stairs. Works on ground floor and the last floor but gets stuck on the middle floor. When going up to the bank it works every time. Also it may randomly work sometime after xx tries but it can take half a minute or more so it's not a solution.

![WalkDontWork](https://user-images.githubusercontent.com/41478174/63217812-322d8f80-c14d-11e9-99f7-19b16bf56364.png)

**Comment by Lezor91** [comment]
Duplicate

https://github.com/rs-peer/issues/issues/360
