### ISSUE TITLE
Clear game data at logout?

### ISSUE THREAD

**Issue by aids9345435345kek** [rs-peer/issues#392]
When i login to an account then log out i can still access my account's game data such as stats, position, etc, from the logout screen through Player & Skills. This is not replaced with the next acc's game data until some time after i log into the next account, it also doesn't get replaced all at once, meaning if i do getName() != previousAccDisplayName (to validate game data has changed), this doesn't guarantee i'm not getting the previous acc's Skills or position data, which i need in my script ASAP after login to validate tasks.

This is also not script related as i can start a new script at the login screen to obtain the data including the player instance as long as i have previously logged into an acc on the client.

Can't seem to find any work around for this.

**Comment by Lezor91** [comment]
Please provide code to reproduce this.

**Comment by aids9345435345kek** [comment]
https://pastebin.com/KxwADE9e

https://streamable.com/lfa5d

**Comment by Lezor91** [comment]
That's normal and just how the game works? 

I can't see how it'd affect your tasks as it's only an issue when logged out and everything is instantly updated on login
