### ISSUE TITLE
Add enums for gamestates

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#40]

**Comment by ZachHerridge** [comment]
Example implementation here https://github.com/Acuity/AcuityCore/blob/master/acuity-api/src/main/java/com/acuity/api/rs/utils/Game.java

**Comment by SPEN-CER** [comment]
The values for game states already exist as constants in the Game class.
See [full list of constant values here](https://rspeer.org/javadocs/constant-values.html)
