### ISSUE TITLE
Varp Debugger causing overflow and crashing

### ISSUE THREAD

**Issue by Typiqally** [rs-peer/issues#401]
When I click on the varp (0) RSPeer quickly freezes and finally crashes.

Reproducing:
1. Open the client, let it load (don't login to your RS account)
2. Open the Varp Debugger
3. Login with a RS account
4. Look at the Varp Debugger (if it's empty enter something into the search field and then remove it)
5. Click on the last Varp (0)

**Comment by joey-colon** [comment]
@mad please answer
