### ISSUE TITLE
Position.isPositionWalkable falsely returns true under multi-tile SceneObjects

### ISSUE THREAD

**Issue by kerowak** [rs-peer/issues#402]
If you get the position of a SceneObject and enumerate its neighbors, those tiles will return true for isPositionWalkable even if they lie within the footprint of the SceneObject and are unreachable.

This makes it difficult to enumerate the positions from which the player is able to interact with the SceneObject (access points,) which are important for many different types of scripts.

Additionally, the inability to list the positions which a SceneObject occupies makes it even more difficult to enumerate its access points. Can I make an enhancement request for the addition of such a feature?

**Comment by MaddoxDevelopment** [comment]
Have you tried Movmement.isWalkable(pos, false) or Movement.isInteractable(pos, false);

The second parameter is acceptEndBlocked, try that as false.

**Comment by kerowak** [comment]
That does the trick. What's the purpose of isInteractable?

**Comment by MaddoxDevelopment** [comment]
Objects that are blocking but can be interacted with to remove the block, such as Doors.

**Comment by kerowak** [comment]
Thanks Mad
