### ISSUE TITLE
RSPeer NullPointerException

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#410]
https://i.vgy.me/6OSvSI.gif

Couldn't get the stacktrace from the command line as I'm launching bots through my own launcher.

**Comment by MzScorpio** [comment]
It's an issue with using a world that doesn't exist on RuneScape in the quickstart args.
Maybe we could get around this by making RSPeer redirect to an existing world if the selected world is invalid.

**Comment by buracc** [comment]
just select an existing world?

**Comment by MzScorpio** [comment]
> 
> 
> just select an existing world?

I was doing that until they changed the worlds. It's all automated.
