### ISSUE TITLE
WorldHopper.randomHopInF2p() tries to hop to twisted league worlds

### ISSUE THREAD

**Issue by flakeydabanana** [rs-peer/issues#414]
WorldHopper.randomHopInF2p() attempts to jump to world 409 which is a twisted league world, resulting in the client landing on the login screen and spamming it.

**Comment by Lezor91** [comment]
I don't think this method has *ever* filtered out worlds based on requirements/activity whether that be twisted league or total levels and I'm not sure if I want to change the behavior for it. 

Use `randomHop(java.util.function.Predicate<? super RSWorld> predicate)`
