### ISSUE TITLE
Account creation page launched in browser

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#419]
Not exactly sure what's causing this but it happens randomly for banned accounts.

URL being opened: secure.runescape.com/m=account-creation/g=oldscape/create_account

**Comment by Eclipseop** [comment]
Are you using a custom login handler?

**Comment by MzScorpio** [comment]
Yeah, not using clicks at all though.

**Comment by buracc** [comment]
It opens on all new accounts. Happens to me too on my own client.

**Comment by Lezor91** [comment]
Filtered out for the next build.
