### ISSUE TITLE
Web walker tries to teleport without having the required level

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#420]
I tried opening the spell book as suggested [here](https://github.com/rs-peer/issues/issues/227) but it is still trying to teleport.

The fact is I don't even want it to use teleports at this stage, I just have the runes for another usage later on. We should have an option implemented to disable the usage of teleports (or enable it) while building a path to a certain position.

P.S. I'm using acuity

**Comment by Lezor91** [comment]
#360
