### ISSUE TITLE
[Suggestion] Add BankLocation#ZANARIS

### ISSUE THREAD

**Issue by David-Rodden** [rs-peer/issues#423]
Currently not supported - there are bank chests & fairy bankers located around Position `(2381, 4458, 0)`

**Comment by Lezor91** [comment]
The reason certain banks like this are not added is because we don't have code to check if you meet the requirements. If you can provide me with the var/varbit index and completion value for the lost city quest I can add this.

**Comment by Man16** [comment]
> The reason certain banks like this are not added is because we don't have code to check if you meet the requirements. If you can provide me with the var/varbit index and completion value for the lost city quest I can add this.

public static boolean completedLostCity() {
        return Varps.get(147) == 6;
    }

**Comment by Lezor91** [comment]
Thank you. Added for the next build
