### ISSUE TITLE
Area.polygonal incorrect results

### ISSUE THREAD

**Issue by BitScorpio** [rs-peer/issues#48]
The **contains** method returns incorrect results. Using Java's AWT Polygon with the same coordinate positions works just fine. (Area created using the Map Utility window)

**Comment by SPEN-CER** [comment]
Are you sure about this? The Polygonal implementation of Area that we have is backed by `java.awt.Polygon`, so it seems strange to me that they would be producing different results. Please make sure you are running the latest version of the bot!
