### ISSUE TITLE
Incorrect script being started

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#52]
Occasionally the incorrect script is started regardless of the script selected. I haven't been able to figure out what causes this as it seems to be random.

This example shows the script that should be started is the SPX AIO Walker, but instead is the Test Task Script.
[![Image from Gyazo](https://i.gyazo.com/8d6a0261fc3be7707fb5b36315c39684.gif)](https://gyazo.com/8d6a0261fc3be7707fb5b36315c39684)

**Comment by SPEN-CER** [comment]
Fixed
