### ISSUE TITLE
sceneobject floor level bug

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#58]
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: SceneObject false Position[x=2474, y=3435, level=0]
> 
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: Position Position[x=2474, y=3435, level=0]
> 
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: fromSceneObject false Position[x=2474, y=3435, level=-320]
> 
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: fromPosition true Position[x=2474, y=3435, level=0]
> 
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: newPosition true Position[x=2474, y=3435, level=0]
> 
> [FINE] Wed Jul 04 18:43:18 PDT 2018: Fine: .getProvider().getClass().getSimpleName() dx

`             Area area = Area.rectangular(2470, 3437, 2478, 3433, 0);
            SceneObject log = SceneObjects.getNearest("Log balance");
            Log.fine("SceneObject " + area.contains(log) +" "+ log.getPosition());
            Position position = log.getPosition();
            Log.fine("Position " + position);
            Position fromSceneObject = new Position(log.getX(), log.getY(), log.getFloorLevel());
            Log.fine("fromSceneObject " + area.contains(fromSceneObject) +" "+ fromSceneObject);
            Position fromPosition  = new Position(position.getX(), position.getY(), position.getFloorLevel());
            Log.fine("fromPosition " + area.contains(fromPosition) +" "+ fromPosition);
            Position newPosition = new Position(2474, 3435, 0);
            Log.fine("newPosition " + area.contains(newPosition) +" "+ newPosition);
            Log.fine(".getProvider().getClass().getSimpleName() " + log.getProvider().getClass().getSimpleName());
`

sceneobject floor level is cucked

**Comment by dQw4w9WgXcQ** [comment]
yikes that code formatting

**Comment by SPEN-CER** [comment]
Fixed for the next build
