### ISSUE TITLE
Enhancement: add low cpu button to menubar

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#68]
also, imo remove low cpu/super low cpu and just keep super low cpu

pls im getting carpal tunnel

**Comment by dQw4w9WgXcQ** [comment]
i meant just have 1 setting called low cpu that has 80 tick dleay

**Comment by Man16** [comment]
true. i dont see why u would ever use the current low cpu mode instead of the super low

**Comment by SPEN-CER** [comment]
Done
