### ISSUE TITLE
🔥🍕🔥🐸🔥😜🔥improve 🔥 emoji 🔥 in 🔥 logger🔥😜🔥🐸🔥🍕🔥😂😂😂🎊🎉#️⃣6️⃣9️⃣🎉🎊😂😂😂

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#69]
emojis are a vital aspect of modern day communication, but i must say the emojis in the logger look awful and ones in the script title dont even appear!!

please add better emojis!!!

https://i.imgur.com/79dmqQa.png

**Comment by Pizzamaster59** [comment]
support !!!
