### ISSUE TITLE
RenderEvent transparrency on login screen not working as expected

### ISSUE THREAD

**Issue by everskies** [rs-peer/issues#77]
Transparency/Opacity of colors has a strange pulsing behavior in the login screen, works fine once in game.

```
    public void render(Graphics g) {
        g.setColor(new Color(0, 0, 0, 100));
        g.fillRect(0, SCREEN_HEIGHT - OVERLAY_HEIGHT, SCREEN_WIDTH, OVERLAY_HEIGHT);
    }
```
Gif:

![overlayflashing](https://user-images.githubusercontent.com/17406493/42422695-38c5b800-82eb-11e8-8b9c-7854d9ccd947.gif)

![image](https://user-images.githubusercontent.com/17406493/42422725-f057490c-82eb-11e8-8c34-ea5167c43923.png)

**Comment by SPEN-CER** [comment]
This is just the way that jagex renders on the login screen, the rates are different to what they are in game.
