### ISSUE TITLE
login handler wont log in on latest ver

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#97]

**Comment by dQw4w9WgXcQ** [comment]
nvm its working again? idk

**Comment by dQw4w9WgXcQ** [comment]
it fails like 3/4 the time

**Comment by SPEN-CER** [comment]
What do you mean fails? Can you elaborate?

**Comment by dQw4w9WgXcQ** [comment]
https://i.imgur.com/pStfYVE.png

gets to this point, only clicks the Login button 1/4 the times LoginScreen.process() is called.

**Comment by SPEN-CER** [comment]
Fixed
